名称：自动更新工作器

在：
  推送:
    分支：
      输入：主要
  时间表:
    - cron: "0 1 * * *" # 每天凌晨1点自动运行
  workflow_dispatch:     # 支持手动运行

权限：
  内容：写

工作：
  更新：
    运行于：ubuntu-latest
    步骤：
      - 名字: 初始化仓库
        用途：actions/checkout@v4

      - 名字: 获取当前本地版本
        id： 获取本地版本
        运行： |
          echo -e "\033[34m[获取本地版本]\033[0m"
          if [ -f version.txt ]; then
            LOCAL_VERSION=$(cat version.txt)
            echo "当前本地版本: $LOCAL_VERSION"
          否则
            echo "首次同步，没有本地版本。"
            LOCAL_VERSION=""
          输入：          fi
          echo "LOCAL_VERSION=$LOCAL_VERSION" >> $GITHUB_ENV

      - 名字: 获取最新 Release 信息
        id： 获取版本
        运行： |
          echo -e "\033[34m[获取最新 Release]\033[0m"
          API_URL="https://api.github.com/repos/bia-pain-bache/BPB-Worker-Panel/releases"
          RESPONSE=$(curl -s "$API_URL")
          LATEST_RELEASE=$(echo "$RESPONSE" | jq -r '.[0]')
          TAG_NAME=$(echo "$LATEST_RELEASE" | jq -r '.tag_name')
          DOWNLOAD_URL=$(echo "$LATEST_RELEASE" | jq -r '.assets[] | select(.name == "worker.zip") | .browser_download_url')

          if [ -z "$DOWNLOAD_URL" ] || [ "$DOWNLOAD_URL" == "null" ]; then
            echo -e "\033[31m未找到 worker.zip，退出！\033[0m"
            退出 1
          输入：          fi

          echo "最新版本号: $TAG_NAME"
          echo "DOWNLOAD_URL=$DOWNLOAD_URL" >> $GITHUB_ENV
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - 名字: 判断是否需要更新
        id： 检查更新
        运行： |
          echo -e "\033[34m[判断是否需要更新]\033[0m"
          if [ "$LOCAL_VERSION" = "$TAG_NAME" ]; then
            echo -e "\033[32m已经是最新版本，无需更新。\033[0m"
            echo "UPDATE_NEEDED=false" >> $GITHUB_ENV
          否则
            echo -e "\033[33m发现新版本，需要更新！\033[0m"
            echo "UPDATE_NEEDED=true" >> $GITHUB_ENV
          输入：          fi

      - 名字: 如果需要，清理旧文件并下载新版本
        如果： env.UPDATE_NEEDED == '真'
        运行： |
          echo -e "\033[34m[清理旧文件]\033[0m"
          rm -rf ./*
          echo -e "\033[34m[下载最新 worker.zip]\033[0m"
          wget -O worker.zip "$DOWNLOAD_URL"
          echo -e "\033[34m[解压 worker.zip]\033[0m"
          解压 worker.zip
          echo -e "\033[34m[删除 worker.zip]\033[0m"
          rm worker.zip
          echo -e "\033[34m[记录新版本号]\033[0m"
          echo "$TAG_NAME" > version.txt

      - 名字: 提交更改
        如果： env.UPDATE_NEEDED == '真'
        使用： stefanzweifel/git-auto-commit-action@v5
        与：
          提交信息："🔄 自动同步最新 Worker 版本：${{ env.TAG_NAME }}"
          提交作者: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          推送选项：--force
